# Generated by Django 2.1.5 on 2019-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
